### ISSUE TITLE
No funcionan botones de crear nuevo mapa, importar desde moodle de inicio

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#102]
![image](https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/assets/125374554/a0df1349-882a-492e-a0ba-5afe5c9d0d48)

No funcionan los botones de inicio, en el caso de importar desde moodle da este error en la consola:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'platform')

Los botones de la barra superior sí.

Código actualizado a la última versión de hoy

**Comment by jumarub** [comment]
This error does not occur in version 0.8; the issue is related to the migration of certain files to tsx. We are working on it.
