### ISSUE TITLE
Discrepancias entre el bloque seleccionado (lineas punteadas) y la información de la barra lateral #10091

### ISSUE THREAD

**Issue by jumarub** [uniadaptiveLTI/uniadaptiveLTI-Front#19]
Hay discrepancias entre el bloque seleccionado (lineas punteadas) y la información de la barra lateral
Las líneas punteadas que señalan el foco en la aplicación se pierden cuando se abre la barra lateral y no se corresponden con el bloque que se está editando

**Comment by Javiondox** [comment]
Should be fixed right now. Reopen if needed.
