### ISSUE TITLE
V5 - Validación de bloques abstractos no convertidos a instancias #10098

### ISSUE THREAD

**Issue by jumarub** [uniadaptiveLTI/uniadaptiveLTI-Front#21]
V5 - Validación de bloques abstractos no convertidos a instancias
Si tenemos un bloque al que le quitamos el elemento asociado y guardamos, no aparece la exclamación roja y el módulo de validación tampoco indica error

**Comment by Javiondox** [comment]
Should be fixed right now. Reopen if needed.
