### ISSUE TITLE
Hay que salir de la plataforma para que se vean los cambios entre versiones #10106

### ISSUE THREAD

**Issue by jumarub** [uniadaptiveLTI/uniadaptiveLTI-Front#23]
Cuando creas una nueva versión y haces modificaciones, tienes que salir de la plataforma para que se vean los cambios entre versiones

**Comment by Javiondox** [comment]
This bug is a big one and needs to move some logic from the Front End to the Back End and vice versa.

**Comment by rafaugr** [comment]
Hay que reabrir esta tarea tal y como se mencionó aquí:
https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/pull/83#issuecomment-1857434560

**Comment by uniadaptive** [comment]
Reabrimos, siguiendo el comentario de 15 de diciembre que se indica que dice:
> Código actualizado y sigue pasando.
> Si cambias entre versiones sin guardar, parece que se reflejan los cambios de eliminación de nodos, no así en los cambios de ordenación. Pasos para reproducir el error:
> 1. Creas una nueva versión desde la opción "Nueva versión desde la actual"
> 2. Eliminas un nodo
> 3. Guardas con el botón guardar
> 4. Vuelves a la versión anterior (está el nodo eliminado de forma correcta)
> 5. Vuelves a la última versión donde el nodo ya estaba eliminado y sigue apareciendo.

**Comment by rafaugr** [comment]
> Reabrimos, siguiendo el comentario de 15 de diciembre que se indica que dice:
> 
> > Código actualizado y sigue pasando.
> > Si cambias entre versiones sin guardar, parece que se reflejan los cambios de eliminación de nodos, no así en los cambios de ordenación. Pasos para reproducir el error:
> > 
> > 1. Creas una nueva versión desde la opción "Nueva versión desde la actual"
> > 2. Eliminas un nodo
> > 3. Guardas con el botón guardar
> > 4. Vuelves a la versión anterior (está el nodo eliminado de forma correcta)
> > 5. Vuelves a la última versión donde el nodo ya estaba eliminado y sigue apareciendo.

Sigue pasando siguiendo exactamente estos pasos
