### ISSUE TITLE
Cuando se eliminan elementos, algunas veces falla #10113

### ISSUE THREAD

**Issue by jumarub** [uniadaptiveLTI/uniadaptiveLTI-Front#26]
Cuando se eliminan elementos, algunas veces falla.

**Comment by jumarub** [comment]
To resolve the issue, we need more information about the error execution process.

**Comment by rafaugr** [comment]
En el ticket original de Jira, adjunté este vídeo: https://drive.google.com/file/d/18kilXA3sAW50WL6ojeDMqONXa9ea2dQC/view?usp=drive_link
Ahora, en principio, no reproduzco el error.

**Comment by Javiondox** [comment]
We are going to mark it as solved, if it is not the case, it can be reopened.
