### ISSUE TITLE
Cuando hay errores en la validación el botón de guardar está disponible

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#32]
Cuando hay errores en la validación, el botón de guardar sigue estando disponible y hace un proceso que luego no devuelve ningún tipo de retroalimentación al usuario sobre si se ha podido o no enviar el itinerario

![image](https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/assets/125374554/2c455654-2e6b-40ad-af3d-f76c7d57e412)

#27 está marcado como cerrado cuando debe ser corregido

**Comment by jumarub** [comment]
To resolve the issue, we need more information about the error execution process. Since it works correctly in our local environment, has a map created in another version of the project been used?

**Comment by rafaugr** [comment]
Se puede ver aquí: https://drive.google.com/file/d/1ue8IQv46wqI-mFnVkwXHLWyNieVWB_90/view?usp=drive_link

**Comment by Javiondox** [comment]
We know that the images you provide us come from the video you have passed. What we do not know is whether the map was created or not previously in an old version of the tool, it is imported from Moodle…

**Comment by rafaugr** [comment]
Cuando creas un nuevo mapa vacío, y algunas veces cuando importas desde moodle, el botón de guardar y exportar sigue activo con errores de validación en el mapa y no ofrece información del motivo del fallo cuando pulsas. Reabrid, por favor.
