### ISSUE TITLE
Interaccionar con las líneas para editar la precondición

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#33]
Mecanismos de click derecho o doble click que permitan configurar la precondición desde la flecha

**Comment by jumarub** [comment]
The improvements to be applied are as follows:

For Moodle:

- Edit condition for a common block (quiz, assignment, etc.)
- Edit condition for an action block (badge)

For Sakai:

- Edit condition for a common block (quiz, assignment, etc.)

**Comment by rafaugr** [comment]
Se va a hacer merge con la rama main?

**Comment by jumarub** [comment]
Se hará un merge de la versión 0.8 cuando se realice la integración del V6 y algunas refactorizaciones de código TSX
