### ISSUE TITLE
Debería de indicar si algo previamente importado desde moodle no está soportado por la herramienta LTI. (precondiciones, bloques, …)

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#35]
Ahora los mantiene, pero no hace ninguna indicación de que existen precondiciones no soportadas por las herramientas, ni se puede establecer una relación entre ellas. Aunque no se pudieran editar debería manejarlas.

**Comment by jumarub** [comment]
This improvement will be implemented as follows:

- Import support for creating generic conditions that store the code of unsupported conditions.

- Support at visual level within the modal conditions

- Visual level support within the condition summary when hovering on a block

- Export support to maintain the moodle condition structure
