### ISSUE TITLE
V6 - Validación de instancias de bloque no utilizados en el diseño

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#48]
No informa de que hay elementos del curso que no están añadidos al itinerario

**Comment by rafaugr** [comment]
Hola, esto no es una mejora, era un requisito obligatorio.

**Comment by jumarub** [comment]
We are testing both environments (Moodle and Sakai) to verify their integrity.

**Comment by jumarub** [comment]
These commits add a new section to the export screen. In the case of Moodle, it will display the modules that are not present on the map but are in the current course. For Sakai, it will show the missing modules compared to the selected lesson in the export screen dropdown.

https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/commit/58ffc85d305cc99e3fc8ee69ef7507ce78cf98dd
https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/commit/8fc7e24ade33f2a50079081124e99d08b4a7e995
https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/commit/1e17341afe62edf79830e7792f8c78ed2255733d
https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/commit/de8f49dd2da59dce1f118905e5a549eabf1d92c6
https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/commit/5bd26a12731496b690ec4186aecdad6210b88c84
https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/commit/2ff6a27816a72289cc8fbf3629df3231532d1e37
