### ISSUE TITLE
Agregar al interfaz el curso que se está editando y en la instancia en la que está

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#64]
Se muestra el curso pero no se indica la instancia de la plataforma (abierta, prado...)

Hablado en: S1-2.5

**Comment by Javiondox** [comment]
Instance name has been added to the main branch. PR #100

**Comment by rafaugr** [comment]
¿Dónde aparece el nombre de la instancia?

**Comment by Javiondox** [comment]
The name of the instance needs to be determined in multiple.lms.config. The front end, upon receiving the get_session call, will receive the "platform_name" parameter in addition to "platform" (this being the name of the instance).

In the interface, if the instance has a defined name (which is optional), it replaces the platform name under the user's name with the instance name. The platform is displaced under a new tooltip for help on user information.

This will be explained in more detail in the documentation of the next version.
