### ISSUE TITLE
C3 - Comprobación de integridad antes del envío de diseño #10096

### ISSUE THREAD

**Issue by Javiondox** [uniadaptiveLTI/uniadaptiveLTI-Front#71]
C3 - Comprobación de integridad antes del envío de diseño
En el pliego se ejemplificaba que al menos comprobara que no se eliminan del itinerario elementos ya calificados. No está funcionando así.

**Comment by Javiondox** [comment]
Should be fixed right now. Reopen if needed.

**Comment by Javiondox** [comment]
Seemingly, it doesn't work.

**Comment by jumarub** [comment]
As marked on #73, we close the issue
