### ISSUE TITLE
C3 - Comprobación de integridad antes del envío de diseño

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#73]
Cerrado en #71 
Hemos probado, y no nos avisa que hemos borrado del itinerario un elemento que ya había sido calificado

**Comment by Javiondox** [comment]
#71

**Comment by jumarub** [comment]
@rafaugr
The resource grading notification system is working locally. On the Moodle grades tab, the resource is marked as completed by at least one person. Can you verify if the resource in question has a grade?

If it does, could you please send a screenshot of the browser console (F12) and paste the JSON message (LMS_DATA) to provide more context for the issue?

Thank you very much.

**Comment by rafaugr** [comment]
Parece que ahora funciona mejor. Cuando se va a eliminar un elemento calificado, aparece una ventana que lo indica y pide confirmación.
