### ISSUE TITLE
Cuando hay errores el botón está disponible para guardar y exportar

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#75]
![image](https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/assets/125374554/0f9cf574-e877-4f07-a7d2-66008d3d0a2a)
Como se puede ver en la imagen adjunta, hay errores y el botón de guardar está habilitado. Además, si se pulsa no informa de nada (falla porque hay un bloque vacío)
Podéis reabrirla?

_Originally posted by @rafaugr in https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/issues/32#issuecomment-1838645469_

**Comment by Javiondox** [comment]
#32
