### ISSUE TITLE
Cuando seleccionas los bloques para crear un fragmento ahora no se aprecia que están seleccionados

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#78]
Relacionado con #53

**Comment by jumarub** [comment]
As requested in issue #19, it was asked that the focus be set when editing a block. Therefore, when a block is edited, it will be marked as the block in editing.

**Comment by rafaugr** [comment]
¿Por qué se ha cerrado?

**Comment by jumarub** [comment]
The issue has been closed because there is already a related incident. Additionally, as resolved in issue #19, the focus was changed when selecting to edit the block. Adding an additional focus for selected blocks to create a fragment now corresponds to issue #53.
