### ISSUE TITLE
Cuando hay un bloque de consulta en el mapa, no se puede exportar

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#80]
Si hay un bloque de consulta, no se puede guardar ni el mapa completo, ni la unidad suelta en la que está.

export_version devuelve: 
{ok: false, errorType: "ERROR_OCURRED"}
errorType
: 
"ERROR_OCURRED"
ok
: 
false

**Comment by jumarub** [comment]
For future issues, it would be advisable to differentiate between saving using the save button and exporting using the corresponding button. This is because it has been mentioned that the export_version is returning an error, so the export button is being used instead of the save button.

**Comment by jumarub** [comment]
The error occurs when the map is not exported in the presence of a query block, causing the map not to be saved correctly. We are working on addressing this issue and will provide further updates once it is resolved. Thank you.

**Comment by Javiondox** [comment]
Closing issue. Comment here to reopen the issue if it persists.
