### ISSUE TITLE
Eliminación de elementos del mapa

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#81]
Si se elimina un elemento de mapa, debería eliminar sus precondiciones y avisarlo mediante una ventana de confirmación. Puede ocurrir que si se importa de nuevo desde moodle ese elemento eliminado va a volver con las precondiciones obsoletas.

**Comment by Javiondox** [comment]
When you import a resource in an existing map, you are creating a new abstract block without any conditions. The only way to get the obsolete conditions is to import another map without committing the conditions.

**Comment by rafaugr** [comment]
Me refiero a que si vuelves a crear un mapa con la opción "Nuevo mapa desde moodle" el elemento viene con las precondiciones anteriores a su eliminación.

**Comment by Javiondox** [comment]
When you press a "Nuevo mapa desde Moodle" you effectively create a new map using the current resources in Moodle.

If you delete a resource in Moodle and import, it shouldn't be imported. If this is the case, can you proportionate a image of the course layout and the final map?

If you delete elements in a map, even if you export it, you aren't deleting those elements on moodle. Only hiding them. If you are deleting, exporting and importing, you shouldn't see any changes as the resources stay in the same place, waiting to be used.

**Comment by jumarub** [comment]
![image](https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/assets/91719773/f1b3ffeb-17a3-425a-8d7b-9da13b61c62b)
