### ISSUE TITLE
Cuando se importa desde moodle un curso con insignias da error

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#82]
error en components/Header.js:390

Unhandled Runtime Error
ReferenceError: nodes is not defined

**Comment by Javiondox** [comment]
Can you explain when this occurs, without context is impossible to know.

**Comment by jumarub** [comment]
The issue appears to be related to a change in variable naming convention, where "nodes" should be replaced with "NODES." If the error persists, please provide more context about the problem for further investigation.

**Comment by rafaugr** [comment]
Con el código actualizado a la versión actualizada ayer, ahora el error es el siguiente:
`Uncaught (in promise) ReferenceError: NEW_NODE is not defined
    at parseMoodleBadges (Moodle.js:55:2)
    at eval (Header.js:419:34)
    at Array.map (<anonymous>)
    at handleImportedMap (Header.js:418:26)`

Pasos para reproducir el error:

1. Abrir la herramienta desde un curso que tiene insignias
2. Importar desde moodle

**Comment by jumarub** [comment]
In both commits, the issue has been resolved. Thank you.

**Comment by Javiondox** [comment]
It will be merged to the main project via Pull Request in short.

**Comment by Javiondox** [comment]
Closing issue. Comment here to reopen the issue if it persists.
