### ISSUE TITLE
Guardando un cambio de color en el admin del front da error

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#85]
![image](https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/assets/125374554/34a82a24-24ea-4d23-9e1c-6e1c8d885dc4)
Al dale a modificar para guardar un cambio de colores no muestra ningún error ni hace nada. Solo en la consola se ve lo que adjunto en la imagen.

**Comment by Javiondox** [comment]
Will be looked upon if the issue persists after #68

**Comment by rafaugr** [comment]
cómo se configura ahora el acceso al panel de administración? porque /admin da 404

**Comment by rafaugr** [comment]
sigue dando el mismo error actualizado el código a la misma versión. Reopen.

**Comment by rafaugr** [comment]
Hay que reabrir esta tarea. Gracias.

**Comment by rafaugr** [comment]
Esta tarea se cerró y no está solucionado

**Comment by jumarub** [comment]
We have made a small change that prevents clicking on the sections. Regarding the error when saving colors, this issue is not present in our local environment, and it seems to no longer occur.

**Comment by rafaugr** [comment]
La funcionalidad de pinchar en los elementos de la interfaz la habéis eliminado?

**Comment by jumarub** [comment]
The functionality has not been removed, changes were made due to a small error when clicking on different elements.
