### ISSUE TITLE
Se permite exportar cuando hay errores tras cargar un fichero de un mapa.

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#90]
Forma de reproducir el bug:

1. Importar un fichero de un mapa guardado de otro curso
2. Aparecen correctamente los bloques abstractos con las exclamaciones que indican que no tienen un elemento del LMS asociado.
3. Le damos al botón de exportar de la barra superior para exportar el mapa y no indica que tenemos errores.
4. El botón de Guardar y Exportar está disponible cuando no debería

**Comment by jumarub** [comment]
Yesterday, 10/01/2024, several changes were merged, one of them being a modification in the logic related to the export modal. Could you pull the changes and check if the issue still occurs? It appears to be resolved in our local environment.

**Comment by jumarub** [comment]
We assume that the bug is fixed in the current version, otherwise it will be reopened. Thank you
