### ISSUE TITLE
No se reflejan los cambios en el lms

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#92]
Reproducción:
1. Versión del código actualizada
2. Importas desde moodle o creas un nuevo mapa
3. Modificas el orden de algún elemento o creas alguna precondición
4. Le das al botón de guardar y exportar
Sale exportación correcta pero no se refleja ningún cambio en el LMS.

**Comment by rafaugr** [comment]
Esto pasa también en: https://moodle.silta-dixit.com

**Comment by jumarub** [comment]
The bug has been fixed locally, the https://moodle.silta-dixit.com version will be updated shortly.
