### ISSUE TITLE
No indica los permisos que necesita el usuario del webservice

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#96]
En la nueva documentación sigue sin indicar los permisos que necesita el usuario del webservice.

**Comment by jumarub** [comment]
This has been marked as an improvement because the documentation will be updated to notify of the required permissions, one improvement would be to create a default Uniadaptive role with the minimum permissions.

**Comment by jumarub** [comment]
The documentation has been updated with the proposed improvements for version 0.8. Additionally, a role with the minimum permissions required for using the tool has been created. The permissions needed have also been documented in case the user wishes to use another role.
